# Obsidian Publish server — multi-stage build.
#
# Build from the repo root:
#   docker build -t obsidian-publish .
#
# Run (state persists in a volume or bind mount at /data):
#   docker run -d --name obsidian-publish -p 8080:8080 \
#     -v obspub-data:/data \
#     -e OBSPUB_BASE_URL=https://notes.example.com \
#     obsidian-publish
#
# First-run API token: `docker logs obsidian-publish` (printed once).

# --- Stage 1: build the static binary ---------------------------------------
FROM golang:1.26-alpine AS build

WORKDIR /src

# Cache module downloads separately from source changes.
COPY server/go.mod server/go.sum ./
RUN go mod download

COPY server/ ./

# Reproducible, static, CGO-free build (pure-Go SQLite via modernc.org/sqlite).
# -trimpath and -buildvcs=false keep the output independent of the host paths
# and git state; the TARGETARCH build-arg (injected by buildx from the target
# platform) makes one Dockerfile work for amd64 and arm64.
ARG TARGETARCH
RUN CGO_ENABLED=0 GOOS=linux GOARCH=${TARGETARCH} \
    go build -trimpath -buildvcs=false -ldflags="-s -w" \
    -o /out/obsidian-publish-server ./cmd/server

# Empty state dir with correct ownership so the VOLUME is writable by the
# non-root runtime user on first use.
RUN mkdir -p /out/data && chown 65532:65532 /out/data

# --- Stage 2: minimal runtime ------------------------------------------------
# distroless/static: no shell, no package manager, no libc — just enough for a
# static Go binary (plus CA certs and tzdata), running as non-root (65532).
FROM gcr.io/distroless/static-debian12:nonroot

COPY --from=build --chown=nonroot:nonroot /out/obsidian-publish-server /obsidian-publish-server
COPY --from=build --chown=nonroot:nonroot /out/data /data

# All state (SQLite DB, API token, session secret) lives in /data — that is
# the only thing you need to back up.
VOLUME /data

EXPOSE 8080

# Sensible defaults: listen on all interfaces inside the container, keep all
# state under /data. Override OBSPUB_ADDR / OBSPUB_BASE_URL as needed; the
# token and secret files are generated by the server on first start.
ENV OBSPUB_ADDR=:8080 \
    OBSPUB_DB=/data/obsidian-publish.db \
    OBSPUB_TOKEN_FILE=/data/api-token \
    OBSPUB_SECRET_FILE=/data/session-secret \
    OBSPUB_ASSETS_DIR=/data/assets

USER nonroot:nonroot

ENTRYPOINT ["/obsidian-publish-server"]
